export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const CLEAR_CART='CLEAR_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SUB_QUANTITY = 'SUB_QUANTITY';

export const ADD_TO_WISH='ADD_TO_WISH';
export const REMOVE_FROM_WISH='REMOVE_FROM_WISH';
export const CLEAR_WISH='CLEAR_WISH';

export const ADD_USER='ADD_USER';
export const REMOVE_USER='REMOVE_USER';

export const FETCH_PRODUCTS_SUCCESS='FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR='FETCH_PRODUCTS_ERROR'


export const FETCH_PRODUCTS='FETCH_PRODUCTS'
export const SET_LOADER='SET_LOADER'

export const PAGE_LEAVE_ACTION='PAGE_LEAVE_ACTION'

export const GET_USERS='GET_USERS'
export const GET_USERS_SUCCESS='GET_USERS_SUCCESS'
export const GET_USERS_ERROR='GET_USERS_ERROR'
export const FETCH_MEALS_USERS='FETCH_MEALS_USERS'
